# This file is used to configure the VPN siwtcher daemon (vpn-switcherd)

# Times out after 20 seconds
check_timeout_seconds: 20

# The VPN UUID to use if the current network is not trusted
# null means to not use a fallback VPN
fallback_vpn_uuid: null

# The url used to check if the internet is reachable
internet_check_url: http://fedoraproject.org/static/hotspot.txt

# A list of trusted connections
trusted_connections:
# - name: "HomeWifi"
#   uuid: "00000000-0000-0000-0000-000000000000"
# - name: "Another-trusted-network"
#   uuid: "00000000-0000-0000-0000-000000000000"
